"use client";

import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import MainSection from "../components/MainSection";
import Footer from "../components/Footer";
import LoginForm from "@/components/LoginForm";
import Modal from "@/ui/Modal";
import { ModalStore } from "@/mobx/modalStore";
import { modals } from "@/util";
import Message from "@/components/Message";
import { observer } from "mobx-react-lite";

const HomePage = observer(() => {
  return (
    <div>
      <Head>
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Message />

      <Modal
        isOpen={ModalStore.modalName === modals.login}
        closeModal={ModalStore.closeModal}
      >
        <LoginForm />
      </Modal>

      <MainSection />
      <Footer />
    </div>
  );
});

export default HomePage;
