import type { NextPage } from "next";
import Head from "next/head";
import Header from "@/components/Header";
import MainSection from "@/components/MainSection";
import Footer from "@/components/Footer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainSection />
      <Footer />
    </div>
  );
};

export default Home;
